### ISSUE TITLE
Hide console message when it contains "something"

### ISSUE THREAD

**Issue by tuanjr** [games647/ColorConsole#2]
As title said, can you add feature, if console message contains "somethings" (customize in config), it will be hide.

**Comment by tuanjr** [comment]
about new feature you added, it hide message in console, but it still show in log file, so it increase log file size. Can you add option to complete disable message from console + log file?

**Comment by games647** [comment]
I think this might go out of scope of this project. Aren't there already other plugins which can do the same?

**Comment by tuanjr** [comment]
yes, current i use this plugin: https://www.spigotmc.org/resources/console-spam-fix.18410/
but it dont has feature "color" like your plugin.

**Comment by games647** [comment]
Could you use both plugins?

**Comment by tuanjr** [comment]
T_T
